language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - build-tools-27.0.3
    - android-23
    - extra

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-23

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    #- sys-img-armeabi-v7a-android-17